version: "3.8"

services:
  # Database service
  database:
    container_name: project-database
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: project
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # NGINX
  nginx:
    container_name: project-nginx
    restart: on-failure
    image: nginx:1.19.8
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8001:8000
    depends_on:
      - backend
      - frontend

  # Python environment
  backend:
    container_name: project-backend
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      DATABASE_HOST: database
      DATABASE_USER: postgres
      DATABASE_NAME: project
    stdin_open: true
    tty: true
    volumes:
      - ./app/:/home/user/app:delegated
    depends_on:
      database:
        condition: service_healthy
    restart: on-failure

  # Javascript environment
  frontend:
    container_name: project-frontend
    image: node:17-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      # port mapping required for autoreload by websocket
      - 8080:8080
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend